// Ahmed Elmoslmany 2023-01-28 21:03:07
const task1 = document.getElementById('task-1');
const task2 = document.querySelector('li');
const task3 = document.querySelector('#task-1');
const task4 = document.querySelector('ol li');
const task5 = document.querySelectorAll('li')[0];
// const title1 = document.querySelector('title');
// const title2 = document.querySelector('html head title');
const title3 = document.head.querySelector('title');
const h1 = document.querySelector('h1');
task1.style.backgroundColor = 'black'
task1.style.color = 'white'
task2.style.backgroundColor = 'black'
// task3.style.backgroundColor = 'red'
// task4.style.backgroundColor = 'red'
task5.style.backgroundColor = 'red'
task2.style.color = 'white'
title3.textContent = "Assignment - Solved!"
h1.textContent = "Assignment - Solved!"